#!/usr/bin/env bash
cd $GIT_WORK_TREE
sudo -u v4 composer install --no-interaction --prefer-dist --optimize-autoloader
# php artisan migrate --force
php artisan make:sitemap
# npm install
# npm run production
