#!/usr/bin/env python

import sys
import subprocess
import requests
import json

old, new, branch = sys.stdin.read().split()
proc = subprocess.Popen(["git", "rev-list", "--oneline", "--first-parent", "%s..%s" %(old, new)], stdout=subprocess.PIPE)
commitMessage = str(proc.stdout.readlines()[0])

DISCORD_WEBHOOK = sys.argv[1]
MESSAGE = "Changes pushed to https://ioshaven.co\n" + commitMessage

headers = {
    "content-type": "application/json"
}
payload = {
    "content": MESSAGE,
    "username": "Production Server"
}


requests.post(DISCORD_WEBHOOK, data=json.dumps(payload), headers=headers)
